export interface Product {
  id: string
  name: string
  category: "Pax" | "Verifone" | "Sunmi" | "Newland" | "Newpos" | "Nexgo"
  brand: string
  description: string
  features: string[]
  image: string
  price?: string
}


export const products: Product[] = [
  // PAX POS Devices
  {
    id: "pax-a920",
    name: "PAX A920",
    category: "Pax",
    brand: "PAX",
    description: "Advanced Android Smart POS terminal with large touchscreen and integrated printer",
    features: ['5.5" HD touchscreen', "Android OS", "Built-in printer", "4G/WiFi/Bluetooth", "NFC payment"],
    image: "/pax-a920-terminal.jpg",
    price: "Contact for pricing",
  },
  {
    id: "pax-A920 MAX",
    name: "PAX A920 MAX",
    category: "Pax",
    brand: "PAX",
    description: "The MAX is designed to keep you connected in every way possible. A920 MAX delivers a 40% faster install speed and 216% faster reading speed when compared to the A920",
    features: ["6.5' (5G version) capacitive touchscreen", "5G or 4G + WiFi + Bluetooth", "Android 10, 11 or Android 13", "Cortex A53, 1.3 GHz secure processor"],
    image: "/A920 MAX.webp",
    price: "Contact for pricing",
  },
  {
    id: "pax-A920 PRO",
    name: "PAX A920 PRO",
    category: "Pax",
    brand: "PAX",
    description: "Compact in form, powerful in performance. The iconic elegance you know.",
    features: ["Android 14", "Dual-core Cortex A75 processor + Six-Core Cortex A55", "6.56' capacitive touchscreen", "eSIM (NFC Tag)", "5MP front + 8MP rear camera"],
    image: "/A920Pro.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-A910S",
    name: "PAX A910S",
    category: "Pax",
    brand: "PAX",
    description: "Classic with cutting-edge power",
    features: ["Android 10 / 12", "Cortex Quad-core A53/A55 processor", "5' / 5.5' HD touch screen", "4G + WiFi + Bluetooth"],
    image: "/A910S.webp",
    price: "Contact for pricing",
  },

  {
    id: "pax-A8900",
    name: "PAX A8900",
    category: "Pax",
    brand: "PAX",
    description: "Advanced Smart Mobile or Desktop with full touch screen or physical keypad.",
    features: ["Paydroid, powered by Android 12 GO", "Cortex A53 Quad-Core, 2.0GHz", "Chip & PIN | NFC Contactless | Magnetic Stripe", "5.5' 720x1440 Pixels Capacitive Full Touch Scree"],
    image: "/A8900.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-A8700",
    name: "PAX A8700",
    category: "Pax",
    brand: "PAX",
    description: "The ultimate merchant & customer facing device. Running one single processor.",
    features: ["Android 11", "Quad Core 2.0 GHz processor", "7' + 4' capacitive touchscreens", "LAN + WiFi 5.0 + Bluetooth 5.0 and optional 4G", "Contactless + Chip & PIN + 2 Magstripes"],
    image: "/8700.webp",
    price: "Contact for pricing",
  },
  {
    id: "pax-A50 Android MiniPOS",
    name: "PAX A50",
    category: "Pax",
    brand: "PAX",
    description: "All the technology you need in a portable device.",
    features: ["Compact design", "Android 10", "4-inch IPS colour display", "4G + WiFi + Bluetooth", "Durable build"],
    image: "/A50.webp",
    price: "Contact for pricing",
  },

  {
    id: "pax-a80",
    name: "PAX A80",
    category: "Pax",
    brand: "PAX",
    description: "The perfect countertop solution for small & mid-sized businesses",
    features: ["Android 6.0, 7.1 or 10.0", "Cortex A53 processor", "4G connectivity", "4-inch HD touch screen", "Physical keypad"],
    image: "/A80.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-a77",
    name: "PAX A77",
    category: "Pax",
    brand: "PAX",
    description: "The A77 can be carried with you at all times. Weighing as little as 270g and only 17mm thick.",
    features: ["Android 14", "5.5-inch color touchscreen", "4G + WiFi 5Ghz + Bluetooth 5.0", "USB type-C charging port", "Easy to use"],
    image: "/A77.jpeg",
    price: "Contact for pricing",
  },
 {
    id: "pax-a35",
    name: "PAX A35",
    category: "Pax",
    brand: "PAX",
    description: "The ideal payment solution for multilane retailers",
    features: ["Android 10", "4-inch capacitive touch screen", "LAN + WiFi (2.4Ghz/5Ghz) + Bluetooth 4.2", "contactless", "Magnetic stripe", "0.3MP or 5MP front camera"],
    image: "/A77.jpeg",
    price: "Contact for pricing",
  },

  // Verifone POS Devices
  {
    id: "ecr-basic-100",
    name: "ECR Basic 100",
    category: "Nexgo",
    brand: "Makanty",
    description: "Entry-level electronic cash register for small businesses",
    features: ["Easy operation", "Thermal printer", "Cash drawer", "Basic reporting", "Affordable"],
    image: "/ecr-basic-100.jpg",
    price: "Contact for pricing",
  },
  {
    id: "ecr-pro-500",
    name: "ECR Pro 500",
    category: "Nexgo",
    brand: "Makanty",
    description: "Professional ECR with advanced features and reporting",
    features: ["LCD display", "Multiple departments", "Inventory tracking", "Sales reports", "USB connectivity"],
    image: "/ecr-pro-500.jpg",
    price: "Contact for pricing",
  },
  {
    id: "ecr-premium-1000",
    name: "ECR Premium 1000",
    category: "ecr",
    brand: "Makanty",
    description: "Premium electronic cash register with touchscreen",
    features: ["Touchscreen interface", "Advanced reporting", "Network capable", "Employee management", "Cloud backup"],
    image: "/ecr-premium-1000.jpg",
    price: "Contact for pricing",
  },

  // POS Spare Parts & Accessories
  {
    id: "thermal-printer-head",
    name: "Thermal Printer Head",
    category: "pos-parts",
    brand: "Universal",
    description: "Replacement thermal printer head compatible with major POS brands",
    features: ["High durability", "Easy installation", "Universal fit", "1-year warranty", "OEM quality"],
    image: "/thermal-printer-head.jpg",
    price: "Contact for pricing",
  },
  {
    id: "pos-battery-pack",
    name: "POS Battery Pack",
    category: "pos-parts",
    brand: "Universal",
    description: "High-capacity replacement battery for portable POS devices",
    features: ["Extended runtime", "Fast charging", "Safety certified", "Compatible models", "2-year warranty"],
    image: "/pos-battery-pack.jpg",
    price: "Contact for pricing",
  },
  {
    id: "touchscreen-digitizer",
    name: "Touchscreen Digitizer",
    category: "pos-parts",
    brand: "Universal",
    description: "Replacement touchscreen for various POS terminal models",
    features: ["Responsive touch", "Scratch resistant", "Multiple sizes", "Easy replacement", "Quality tested"],
    image: "/touchscreen-digitizer.jpg",
    price: "Contact for pricing",
  },
  {
    id: "pos-power-adapter",
    name: "POS Power Adapter",
    category: "Nexgo",
    brand: "Universal",
    description: "Universal power adapter for POS terminals",
    features: ["Multiple voltages", "Surge protection", "Compact design", "Long cable", "Safety certified"],
    image: "/pos-power-adapter.jpg",
    price: "Contact for pricing",
  },
  {
    id: "charging-dock",
    name: "Charging Dock",
    category: "Nexgo",
    brand: "Universal",
    description: "Multi-device charging dock for POS terminals",
    features: [
      "Charges multiple devices",
      "Cable management",
      "Stable base",
      "LED indicators",
      "Universal compatibility",
    ],
    image: "/pos-battery-pack.jpg",
    price: "Contact for pricing",
  },
  {
    id: "keypad-replacement",
    name: "Keypad Replacement",
    category: "pos-parts",
    brand: "Universal",
    description: "Replacement keypad for POS terminals",
    features: ["Tactile feedback", "Durable construction", "Easy installation", "Multiple layouts", "OEM quality"],
    image: "/touchscreen-digitizer.jpg",
    price: "Contact for pricing",
  },

  // ECR Spare Parts & Consumables
  {
    id: "ecr-paper-roll",
    name: "Thermal Paper Rolls",
    category: "Nexgo",
    brand: "Universal",
    description: "High-quality thermal paper rolls for ECR and POS systems",
    features: ["BPA-free", "Long-lasting print", "Various sizes", "Bulk available", "Eco-friendly"],
    image: "/ecr-paper-roll.jpg",
    price: "Contact for pricing",
  },
  {
    id: "cash-drawer-insert",
    name: "Cash Drawer Insert",
    category: "Nexgo",
    brand: "Universal",
    description: "Replacement cash drawer insert tray",
    features: ["Durable plastic", "Multiple compartments", "Standard size", "Easy to clean", "Secure fit"],
    image: "/cash-drawer-insert.jpg",
    price: "Contact for pricing",
  },
  {
    id: "ecr-keyboard",
    name: "ECR Keyboard",
    category: "Nexgo",
    brand: "Universal",
    description: "Replacement keyboard for electronic cash registers",
    features: ["Tactile keys", "Spill resistant", "Easy installation", "Long lifespan", "Compatible models"],
    image: "/ecr-keyboard.jpg",
    price: "Contact for pricing",
  },
  {
    id: "sim-cards",
    name: "SIM Cards & Data Packs",
    category: "Nexgo",
    brand: "Makanty",
    description: "SIM cards with data packages for POS connectivity",
    features: [
      "Multiple carriers",
      "Data plans included",
      "Easy activation",
      "Nationwide coverage",
      "Flexible packages",
    ],
    image: "/ecr-paper-roll.jpg",
    price: "Contact for pricing",
  },
  {
    id: "security-seals",
    name: "Security Seals & Stickers",
    category: "Nexgo",
    brand: "Makanty",
    description: "Tamper-evident security seals for POS devices",
    features: ["Tamper-evident", "Strong adhesive", "Custom printing", "Various sizes", "Bulk orders"],
    image: "/cash-drawer-insert.jpg",
    price: "Contact for pricing",
  },
]


export const categories = [
  { id: "all", name: "All Products", count: products.length },
  { id: "Pax", name: "Pax", count: products.filter((p) => p.category === "Pax").length },
  { id: "Verifone", name: "Verifone", count: products.filter((p) => p.category === "Verifone").length },
  { id: "Sunmi", name: "Sunmi", count: products.filter((p) => p.category === "Sunmi").length },
  { id: "Newland", name: "Newland", count: products.filter((p) => p.category === "Newland").length },
  { id: "Newpos", name: "Newpos", count: products.filter((p) => p.category === "Newpos").length },
  { id: "Nexgo", name: "Nexgo", count: products.filter((p) => p.category === "Nexgo").length },
]
