export interface Product {
  id: string
  name: string
  category: "Pax" | "Verifone" | "Sunmi" | "Newland" | "Newpos" | "Nexgo"
  brand: string
  description: string
  features: string[]
  image: string
  price?: string
}


export const products: Product[] = [
  // PAX POS Devices
  
  {
    id: "pax-A920 MAX",
    name: "PAX A920 MAX",
    category: "Pax",
    brand: "PAX",
    description: "The MAX is designed to keep you connected in every way possible. A920 MAX delivers a 40% faster install speed and 216% faster reading speed when compared to the A920",
    features: ["6.5' (5G version) capacitive touchscreen", "5G or 4G + WiFi + Bluetooth", "Android 10, 11 or Android 13", "Cortex A53, 1.3 GHz secure processor"],
    image: "/A920 MAX.webp",
    price: "Contact for pricing",
  },
  {
    id: "pax-A920 PRO",
    name: "PAX A920 PRO",
    category: "Pax",
    brand: "PAX",
    description: "Compact in form, powerful in performance. The iconic elegance you know.",
    features: ["Android 14", "Dual-core Cortex A75 processor + Six-Core Cortex A55", "6.56' capacitive touchscreen", "eSIM (NFC Tag)", "5MP front + 8MP rear camera"],
    image: "/A920Pro.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-A910S",
    name: "PAX A910S",
    category: "Pax",
    brand: "PAX",
    description: "Classic with cutting-edge power",
    features: ["Android 10 / 12", "Cortex Quad-core A53/A55 processor", "5' / 5.5' HD touch screen", "4G + WiFi + Bluetooth"],
    image: "/A910S.webp",
    price: "Contact for pricing",
  },
  {
    id: "pax-a920",
    name: "PAX A920",
    category: "Pax",
    brand: "PAX",
    description: "Advanced Android Smart POS terminal with large touchscreen and integrated printer",
    features: ['5.5" HD touchscreen', "Android OS", "Built-in printer", "4G/WiFi/Bluetooth", "NFC payment"],
    image: "/pax-a920-terminal.jpg",
    price: "Contact for pricing",
  },

  {
    id: "pax-A8900",
    name: "PAX A8900",
    category: "Pax",
    brand: "PAX",
    description: "Advanced Smart Mobile or Desktop with full touch screen or physical keypad.",
    features: ["Paydroid, powered by Android 12 GO", "Cortex A53 Quad-Core, 2.0GHz", "Chip & PIN | NFC Contactless | Magnetic Stripe", "5.5' 720x1440 Pixels Capacitive Full Touch Scree"],
    image: "/A8900.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-A8700",
    name: "PAX A8700",
    category: "Pax",
    brand: "PAX",
    description: "The ultimate merchant & customer facing device. Running one single processor.",
    features: ["Android 11", "Quad Core 2.0 GHz processor", "7' + 4' capacitive touchscreens", "LAN + WiFi 5.0 + Bluetooth 5.0 and optional 4G", "Contactless + Chip & PIN + 2 Magstripes"],
    image: "/8700.webp",
    price: "Contact for pricing",
  },
  {
    id: "pax-A50 Android MiniPOS",
    name: "PAX A50",
    category: "Pax",
    brand: "PAX",
    description: "All the technology you need in a portable device.",
    features: ["Compact design", "Android 10", "4-inch IPS colour display", "4G + WiFi + Bluetooth", "Durable build"],
    image: "/A50.webp",
    price: "Contact for pricing",
  },

  {
    id: "pax-a80",
    name: "PAX A80",
    category: "Pax",
    brand: "PAX",
    description: "The perfect countertop solution for small & mid-sized businesses",
    features: ["Android 6.0, 7.1 or 10.0", "Cortex A53 processor", "4G connectivity", "4-inch HD touch screen", "Physical keypad"],
    image: "/A80.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "pax-a77",
    name: "PAX A77",
    category: "Pax",
    brand: "PAX",
    description: "The A77 can be carried with you at all times. Weighing as little as 270g and only 17mm thick.",
    features: ["Android 14", "5.5-inch color touchscreen", "4G + WiFi 5Ghz + Bluetooth 5.0", "USB type-C charging port", "Easy to use"],
    image: "/A77.jpeg",
    price: "Contact for pricing",
  },
 {
    id: "pax-a35",
    name: "PAX A35",
    category: "Pax",
    brand: "PAX",
    description: "The ideal payment solution for multilane retailers",
    features: ["Android 10", "4-inch capacitive touch screen", "LAN + WiFi (2.4Ghz/5Ghz) + Bluetooth 4.2", "contactless", "Magnetic stripe", "0.3MP or 5MP front camera"],
    image: "/A77.jpeg",
    price: "Contact for pricing",
  },

  // Verifone POS Devices
  {
    id: "Verifone T650c",
    name: "Verifone T650c",
    category: "Verifone",
    brand: "Verifone",
    description: "Single-screen checkout and payment. And for developers, an Android OS for easy app development.",
    features: ["Verifone Secure OS Based on Android 8.x", "Barcode and QR Scanning", "ARM Cortex A53, Quad Core, 1.3 GHz", "Bluetooth® v4.2", "PCI PTS 5.x Approved"],
    image: "/verifone-t650c.png",
    price: "Contact for pricing",
  },
  {
    id: "Verifone V400c",
    name: "Verifone V400c",
    category: "Verifone",
    brand: "Verifone",
    description: "Ideal for retail, banking, hospitality, drug stores, quick/casual dining and more.",
    features: ["ARM Cortex A9, 600 MHz", "Integrated Printer: 40mm Paper Roll | Prints 30lps", "3.5' Color LCD Touchscreen", "128MB RAM + 256MB Flash"],
    image: "/Verifone-V400c.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-v200c",
    name: "verifone-v200c",
    category: "Verifone",
    brand: "Verifone",
    description: "Easily engage your customers with the vibrant color LCD and sound capabilities that drive multimedia.",
    features: ["EMVCo and PCI 5.x Approved", "Verifone secure OS", "Supports Major NFC/contactless Schemes", "MSR and Smart Cards"],
    image: "/verifone-v200c.png",
    price: "Contact for pricing",
  },

  
  {
    id: "verifone-e235",
    name: "verifone-e235",
    category: "Verifone",
    brand: "Verifone",
    description: "The Verifone e235 is perfect for tier two or tier three retailers, QSRs, small business operators, entertainment venues and many other use cases",
    features: ["High durability", "Slim and Light Weight", "2.3' Color LCD, LED Backlight", "Speaker, Tactile 15 Key Keypad"],
    image: "/verifone-e235.png",
    price: "Contact for pricing",
  },
  {
    id: "e280s",
    name: "e280s",
    category: "Verifone",
    brand: "Verifone",
    description: "From food delivery to food trucks, easily accept payments on-the-go when the e280 / e280s is paired with Verifone's iOS/Android point of sale app and gateway.",
    features: ["Capacitive touchscreen", "Connect via WiFi, Bluetooth®", "Low energy usage", "Multi-charger"],
    image: "/e280s.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-carbon-mobile-5",
    name: "Verifone carbon mobile 5",
    category: "Verifone",
    brand: "Verifone",
    description: "Carbon Mobile 5 enables checkout and the ability to run Android apps, like point of sale, loyalty and inventory management.",
    features: ["LTE / 4G, WiFi, Bluetooth®", "GPS, GLONASS", "Verifone Cloud Services", "Secure Payment Acceptance"],
    image: "/verifone-carbon-mobile-5.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-t650m",
    name: "verifone-t650m",
    category: "Verifone",
    brand: "Verifone",
    description: "Any Payment. Any Scenario. Always Connected.",
    features: ["Fast and Optimal Performance", "Abundant Memory", "WiFi & Bluetooth® Enabled", "Long-Lasting Battery"],
    image: "/verifone-t650m.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-v640m",
    name: "verifone-v640m",
    category: "Verifone",
    brand: "Verifone",
    description: "Create a Delightful Experience for All Your Customers",
    features: [
      "4.3' Color LCD Touchscreen",
      "Verifone Navigator",
      "Supports Major NFC/Contactless Scheme",
      "2G + 3G + 4G CAT 4",
      "ARM Cortex A53, Quad Core, 1.3 GHz",
    ],
    image: "/verifone-v640m.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-v205c",
    name: "verifone-v205c",
    category: "Verifone",
    brand: "Verifone",
    description: "Built for optimal convenience, ease of use and flexibility, the V205c is sure to please.",
    features: ["Ample Memory at 28MB RAM + 256MB Flash", "ARM Cortex A9, 600 MHz Processor", "2.8' Color LCD Screen", "Sound Capabilities"],
    image: "/verifone-v205c.png",
    price: "Contact for pricing",
  },


  {
    id: "verifone-p400",
    name: "verifone-p400",
    category: "Verifone",
    brand: "Verifone",
    description: "Enjoy greater engagement and better returns with a premium PIN pad.",
    features: ["Rich Multimedia Capabilities", "Advanced PIN Pad", "Capacitive Touchscreen", "NFC/CTLS Enabled", "EMVCo Approved"],
    image: "/verifone-p400.png",
    price: "Contact for pricing",
  },
  {
    id: "verifone-p630",
    name: "verifone-p630",
    category: "Verifone",
    brand: "Verifone",
    description: "Easily integrate the 630 into your ECR or Verifone countertop device",
    features: ["Optional QR, barcode and OCR scanning support", "Verifone Secure OS, Engage VOS3|AVOS Based on Android 13", "Supports Advanced Payment Methods", "8 inch Screen"],
    image: "/verifone-p630.png",
    price: "Contact for pricing",
  },
  //Sunmi POS
  {
    id: "v3-family",
    name: "v3-family",
    category: "Sunmi",
    brand: "Sunmi",
    description: "Performance upgrades, tackling multitasking seamlessly",
    features: ["Octa-Core CPU", "Universal Flash Storage (UFS)", "Wi-Fi technology", "Long Runtime Mode"],
    image: "/v3-family.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "v2-pro",
    name: "v2-pro",
    category: "Sunmi",
    brand: "Sunmi",
    description: "The limitless exploration, on your hands.",
    features: [
      "Seiko printhead",
      "2D barcode scan engine",
      "NFC module",
      "Supports a PSAM Card",
      "Dual-Band Wi-Fi",
    ],
    image: "/v2-pro.jpeg",
    price: "Contact for pricing",
  },
  {
    id: "v2s",
    name: "Sunmi v2s",
    category: "Sunmi",
    brand: "Sunmi",
    description: "All the benefits of new SUNMI OS for a better performing device.",
    features: ["Detachable 3500mAh battery", "2D scan engines", "NFC reading", "Android 12 Go Edition", "1GB RAM+8GB ROM"],
    image: "/v2s.jpeg",
    price: "Contact for pricing",
  },
   {
    id: "p2-se",
    name: "Sunmi p2-se",
    category: "Sunmi",
    brand: "Sunmi",
    description: "Designed with versatility in mind.",
    features: ["Accept any electronic payments", "secured fingerprint payment", "NFC Reader", "Magstripe Card", "2D barcode scan engine"],
    image: "/p2-se.jpeg",
    price: "Contact for pricing",
  },
   {
    id: "p2-lite-se",
    name: "Sunmi p2-lite-se",
    category: "Sunmi",
    brand: "Sunmi",
    description: "Pocket smart POS for business on the move.",
    features: ["Support front and rear NFC", "QR Code Payment", "Apple Pay & Samsung Pay", "Robust and Durable"],
    image: "/p2-lite-se.jpeg",
    price: "Contact for pricing",
  },
   
]


export const categories = [
  { id: "all", name: "All Products", count: products.length },
  { id: "Pax", name: "Pax", count: products.filter((p) => p.category === "Pax").length },
  { id: "Verifone", name: "Verifone", count: products.filter((p) => p.category === "Verifone").length },
  { id: "Sunmi", name: "Sunmi", count: products.filter((p) => p.category === "Sunmi").length },
  { id: "Newland", name: "Newland", count: products.filter((p) => p.category === "Newland").length },
  { id: "Newpos", name: "Newpos", count: products.filter((p) => p.category === "Newpos").length },
  { id: "Nexgo", name: "Nexgo", count: products.filter((p) => p.category === "Nexgo").length },
]
